// Hardcoded initial config to bootstrap the Global if empty
export const LEDE_INITIAL_CONFIG = {
  slug: 'lede',
  targets: [
    {
      name: 'inskrywings',
      tabName: 'inskrywings',
      keyField: 'import_id',
      mapping: {
        import_id: 'ID',
        import_name: 'Name',
        created_on_import: 'Created on',
        updated_on_import: 'Updated on',
        responsible_person: 'Responsible person',
        contact_import: 'Contact',
        stage: 'Stage',
        previous_stage: 'Previous stage',
        currency: 'Currency',
        amount: 'Amount',
        last_timeline_activity_by: 'Last timeline activity by',
        last_updated_on_import: 'Last updated on',
        kamp: 'Kamp',
        kamp_kursus: 'Kamp - Kursus',
        lid_import_ref: 'Lid',
        id: 'Lidnommer',
        naam: 'Naam',
        van: 'Van',
        noemnaam: 'Noemnaam',
        kamp_naam: 'Kamp Naam',
        kamp_begindatum: 'Kamp Begindatum',
        kamp_einddatum: 'Kamp Einddatum',
        kamp_ligging: 'Kamp Ligging',
        geboortedatum: 'Geboortedatum',
        geslag: 'Geslag',
        lid_eposadres: 'Lid eposadres',
        kontaknommer_voor_kamp: 'Kontaknommer voor Kamp',
        kontaknommer_tydens_kamp: 'Kontaknommer tydens Kamp',
        kontakpersoon_tydens_kamp: 'Kontakpersoon tydens Kamp',
        eposadres_tydens_kamp: 'Eposadres tydens Kamp',
        kontakpersoon_voor_kamp: 'Kontakpersoon voor Kamp',
        eposadres_voor_kamp: 'Eposadres voor Kamp',
        lid_kontaknommer: 'Lid Kontaknommer',
        skoolgraad: 'Skoolgraad',
        posisie: 'Posisie',
        kommando: 'Kommando',
        ma_volle_naam: 'Ma Volle naam',
        ma_kontaknommer: 'Ma Kontaknommer',
        ma_eposadres: 'Ma Eposadres',
        pa_volle_naam: 'Pa Volle Naam',
        pa_kontaknommer: 'Pa Kontaknommer',
        pa_eposadres: 'Pa Eposadres',
        voog_volle_naam: 'Voog Volle Naam',
        voog_kontaknommer: 'Voog Kontaknommer',
        voog_eposadres: 'Voog Eposadres',
        mediese_fonds_naam: 'Mediese Fonds Naam',
        mediese_fonds_nommer: 'Mediese Fonds Nommer',
        mediese_fonds_afhanklikheidskode: 'Mediese Fonds Afhanklikheidskode',
        allergiee: 'Allergieë',
        mediese_kondisies: 'Mediese Kondisies',
        kroniese_medikasie: 'Kroniese Medikasie',
        mediese_notas: 'Mediese Notas',
        addisionele_notas: 'Addisionele Notas',
        skakel_vir_kurses_opsie_1: 'Skakel vir Kurses Opsie 1',
        kurses_opsie_1: 'Kurses Opsie 1',
        skakel_vir_kurses_opsie_2: 'Skakel vir Kurses Opsie 2',
        skakel_vir_kurses_opsie_3: 'Skakel vir Kurses Opsie 3',
        kurses_opsie_2: 'Kurses Opsie 2',
        kurses_opsie_3: 'Kurses Opsie 3',
        inskrywer_se_epos: 'Inskrywer se epos',
        bevestigingsepos_is_gestuur: 'Bevestigingsepos is gestuur',
        kontak_tipe: 'Kontak tipe',
        opsies: 'Opsies',
        opsie_1_waglys: 'Opsie 1: Waglys',
        opsie_2_waglys: 'Opsie 2: Waglys',
        opsie_3_waglys: 'Opsie 3: Waglys',
        betaling_ontvang: 'Betaling Ontvang',
        products: 'Products',
        soft_shell_baadjies: 'Soft Shell baadjies',
        seejol_hemp_kort: 'Seejol Hemp (Kort)',
        verblyfreelings: 'Verblyfreëlings',
        vervoer_na_mosselbaai: 'Vervoer NA Mosselbaai',
        vervoer_vanaf_mosselbaai: 'Vervoer VANAF Mosselbaai',
        hoeveelste_jaar_kamp_jy_op_seejol: 'Hoeveelste jaar kamp jy op Seejol?',
        qr_skakel: 'QR Skakel',
        qr_prent: 'QR Prent',
      } as Record<string, string>,
    },
    {
      name: 'LidAppData',
      tabName: 'LidAppData',
      keyField: 'id',
      mapping: {
        id: 'Lidnommer',
        noemnaam: 'Noemnaam',
        'divisie.naam': 'Divisie',
        'user.email': 'Gebruiker Epos',
      } as Record<string, string>,
    },
  ],
}
