/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ledeRole".
 */
export type LedeRole =
  | (
      | 'default'
      | 'besoeker'
      | 'ouer'
      | 'kanidaat-jeuglid'
      | 'kanidaat-offisier'
      | 'pd'
      | 'verkenner'
      | 'wagstaan'
      | 'offisier'
      | 'divisieoffisier'
      | 'kombuis'
      | 'logistiek'
      | 'noodoffisier'
      | 'divisieleier'
      | 'kampraad'
      | 'kampleier'
      | 'admin'
    )
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded' | 'pending') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    notificationSubscription: NotificationSubscription;
    media: Media;
    categories: Category;
    users: User;
    lede: Lede;
    inskrywings: Inskrywing;
    divisie: Divisie;
    presensie: Presensie;
    inklokke: Inklokke;
    aktiwiteit: Aktiwiteit;
    groepe: Groepe;
    'puck-templates': PuckTemplate;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
    'payload-query-presets': PayloadQueryPreset;
  };
  collectionsJoins: {
    lede: {
      user: 'users';
      inskrywings_geskiedenis: 'inskrywings';
    };
    divisie: {
      lede: 'lede';
      aktiwiteite: 'aktiwiteit';
    };
    presensie: {
      inklokke: 'inklokke';
    };
    groepe: {
      lede: 'lede';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    notificationSubscription: NotificationSubscriptionSelect<false> | NotificationSubscriptionSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    lede: LedeSelect<false> | LedeSelect<true>;
    inskrywings: InskrywingsSelect<false> | InskrywingsSelect<true>;
    divisie: DivisieSelect<false> | DivisieSelect<true>;
    presensie: PresensieSelect<false> | PresensieSelect<true>;
    inklokke: InklokkeSelect<false> | InklokkeSelect<true>;
    aktiwiteit: AktiwiteitSelect<false> | AktiwiteitSelect<true>;
    groepe: GroepeSelect<false> | GroepeSelect<true>;
    'puck-templates': PuckTemplatesSelect<false> | PuckTemplatesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    'payload-query-presets': PayloadQueryPresetsSelect<false> | PayloadQueryPresetsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    google_sheets_settings: GoogleSheetsSetting;
    sas_import_settings: SasImportSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    google_sheets_settings: GoogleSheetsSettingsSelect<false> | GoogleSheetsSettingsSelect<true>;
    sas_import_settings: SasImportSettingsSelect<false> | SasImportSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path for this page (auto-generated from title)
   */
  slug: string;
  puckData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Which editor was used to create this page
   */
  editorVersion?: ('legacy' | 'puck') | null;
  /**
   * Overall page structure and layout style
   */
  pageLayout: 'default' | 'full-width' | 'landing';
  /**
   * Mark this page as the homepage
   */
  isHomepage?: boolean | null;
  meta?: {
    /**
     * Override the page title for search engines
     */
    title?: string | null;
    /**
     * Description shown in search engine results
     */
    description?: string | null;
    /**
     * Image shown when sharing on social media
     */
    image?: (string | null) | Media;
    /**
     * Prevent search engines from indexing this page
     */
    noindex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    nofollow?: boolean | null;
    /**
     * Exclude this page from the XML sitemap
     */
    excludeFromSitemap?: boolean | null;
  };
  /**
   * Configure conversion tracking for analytics
   */
  conversionTracking?: {
    /**
     * Check this if this page represents a completed conversion (e.g., thank you page)
     */
    isConversionPage?: boolean | null;
    /**
     * Type of conversion this page represents
     */
    conversionType?: ('lead' | 'registration' | 'purchase' | 'donation' | 'newsletter' | 'contact' | 'custom') | null;
    /**
     * Monetary value of this conversion (0 for non-monetary conversions)
     */
    conversionValue?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  emailVerified?: string | null;
  name?: string | null;
  image?: string | null;
  tipe?: ('Jeuglid' | 'Offisier' | 'Ouer') | null;
  self_lid?: (string | null) | Lede;
  gekoppelde_lede?: (string | Lede)[] | null;
  role?: string | null;
  candidate_self_lid_nommer?: string | null;
  candidate_self_lid_dob?: string | null;
  candidate_self_lid_invalid_dob?: boolean | null;
  candidate_gekoppelde_lede?:
    | {
        row_id?: string | null;
        lid_nommer?: string | null;
        dob?: string | null;
        invalid_dob?: boolean | null;
        id?: string | null;
      }[]
    | null;
  accounts?:
    | {
        provider: string;
        providerAccountId: string;
        type: 'oidc' | 'oauth' | 'email' | 'webauthn';
        id?: string | null;
      }[]
    | null;
  sessions?:
    | {
        sessionToken: string;
        expires: string;
        id?: string | null;
      }[]
    | null;
  verificationTokens?:
    | {
        token: string;
        expires: string;
        uses_remaining: number;
        id?: string | null;
      }[]
    | null;
  authenticators?:
    | {
        credentialID: string;
        credentialPublicKey: string;
        credentialBackedUp: boolean;
        counter: number;
        transports?: string | null;
        credentialDeviceType: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lede".
 */
export interface Lede {
  id: string;
  user?: {
    docs?: (string | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  divisie?: (string | null) | Divisie;
  rol?: LedeRole;
  huidige_inskrywing?: (string | null) | Inskrywing;
  naam?: string | null;
  van?: string | null;
  noemnaam?: string | null;
  vertoonnaam?: string | null;
  geboortedatum: string;
  geslag?: string | null;
  skoolgraad?: string | null;
  posisie?: string | null;
  kommando?: string | null;
  hoeveelste_jaar_kamp_jy_op_seejol?: string | null;
  groepe?: (string | Groepe)[] | null;
  lid_inligting_sigbaar_vir_groepe?: (string | Groepe)[] | null;
  lid_eposadres?: string | null;
  lid_kontaknommer?: string | null;
  kontakpersoon_voor_kamp?: string | null;
  kontaknommer_voor_kamp?: string | null;
  eposadres_voor_kamp?: string | null;
  kontakpersoon_tydens_kamp?: string | null;
  kontaknommer_tydens_kamp?: string | null;
  eposadres_tydens_kamp?: string | null;
  ma_volle_naam?: string | null;
  ma_kontaknommer?: string | null;
  ma_eposadres?: string | null;
  pa_volle_naam?: string | null;
  pa_kontaknommer?: string | null;
  pa_eposadres?: string | null;
  voog_volle_naam?: string | null;
  voog_kontaknommer?: string | null;
  voog_eposadres?: string | null;
  mediese_fonds_naam?: string | null;
  mediese_fonds_nommer?: string | null;
  mediese_fonds_afhanklikheidskode?: string | null;
  allergiee?: string | null;
  mediese_kondisies?: string | null;
  kroniese_medikasie?: string | null;
  mediese_notas?: string | null;
  /**
   * From Inskrywing
   */
  kamp?: string | null;
  /**
   * From Inskrywing
   */
  kamp_kursus?: string | null;
  /**
   * From Inskrywing
   */
  kamp_naam?: string | null;
  /**
   * From Inskrywing
   */
  kamp_begindatum?: string | null;
  /**
   * From Inskrywing
   */
  kamp_einddatum?: string | null;
  /**
   * From Inskrywing
   */
  kamp_ligging?: string | null;
  /**
   * From Inskrywing
   */
  kurses_opsie_1?: string | null;
  /**
   * From Inskrywing
   */
  skakel_vir_kurses_opsie_1?: string | null;
  /**
   * From Inskrywing
   */
  kurses_opsie_2?: string | null;
  /**
   * From Inskrywing
   */
  skakel_vir_kurses_opsie_2?: string | null;
  /**
   * From Inskrywing
   */
  kurses_opsie_3?: string | null;
  /**
   * From Inskrywing
   */
  skakel_vir_kurses_opsie_3?: string | null;
  /**
   * From Inskrywing
   */
  opsies?: string | null;
  /**
   * From Inskrywing
   */
  opsie_1_waglys?: string | null;
  /**
   * From Inskrywing
   */
  opsie_2_waglys?: string | null;
  /**
   * From Inskrywing
   */
  opsie_3_waglys?: string | null;
  /**
   * From Inskrywing
   */
  products?: string | null;
  /**
   * From Inskrywing
   */
  soft_shell_baadjies?: string | null;
  /**
   * From Inskrywing
   */
  seejol_hemp_kort?: string | null;
  /**
   * From Inskrywing
   */
  verblyfreelings?: string | null;
  /**
   * From Inskrywing
   */
  vervoer_na_mosselbaai?: string | null;
  /**
   * From Inskrywing
   */
  vervoer_vanaf_mosselbaai?: string | null;
  /**
   * From Inskrywing
   */
  import_id?: number | null;
  /**
   * From Inskrywing
   */
  import_name?: string | null;
  /**
   * From Inskrywing
   */
  lid_import_ref?: string | null;
  /**
   * From Inskrywing
   */
  created_on_import?: string | null;
  /**
   * From Inskrywing
   */
  updated_on_import?: string | null;
  /**
   * From Inskrywing
   */
  last_updated_on_import?: string | null;
  /**
   * From Inskrywing
   */
  responsible_person?: number | null;
  /**
   * From Inskrywing
   */
  contact_import?: number | null;
  /**
   * From Inskrywing
   */
  last_timeline_activity_by?: number | null;
  /**
   * From Inskrywing
   */
  stage?: string | null;
  /**
   * From Inskrywing
   */
  previous_stage?: string | null;
  /**
   * From Inskrywing
   */
  currency?: string | null;
  /**
   * From Inskrywing
   */
  amount?: number | null;
  /**
   * From Inskrywing
   */
  betaling_ontvang?: string | null;
  /**
   * From Inskrywing
   */
  inskrywer_se_epos?: string | null;
  /**
   * From Inskrywing
   */
  bevestigingsepos_is_gestuur?: string | null;
  /**
   * From Inskrywing
   */
  kontak_tipe?: ('Volwassene' | 'Jeuglid') | null;
  /**
   * From Inskrywing
   */
  addisionele_notas?: string | null;
  /**
   * From Inskrywing
   */
  qr_skakel?: string | null;
  /**
   * From Inskrywing
   */
  qr_prent?: string | null;
  inskrywings_geskiedenis?: {
    docs?: (string | Inskrywing)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  syncedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisie".
 */
export interface Divisie {
  id: string;
  number: string;
  naam: string;
  /**
   * Contact information that other divisies can use to get touch with you such as a divisie email or social-media page/handle
   */
  shared_contact?: string | null;
  lede?: {
    docs?: (string | Lede)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  aktiwiteite?: {
    docs?: (string | Aktiwiteit)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aktiwiteit".
 */
export interface Aktiwiteit {
  id: string;
  title: string;
  begin: string;
  einde: string;
  aktiwiteitType: 'robotgame' | 'judging' | 'robotgame-queue' | 'judging-queue' | 'cultural' | 'general';
  beskrywing?: string | null;
  presensie?: (string | null) | Presensie;
  virAlle?: ('divisies' | 'volunteers')[] | null;
  divisies?: (string | Divisie)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presensie".
 */
export interface Presensie {
  naam: string;
  id: string;
  presensie_tipe: 'bus' | 'wagstaan' | 'divisie';
  inklokke?: {
    docs?: (string | Inklokke)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  verwagte_lede?: (string | Lede)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inklokke".
 */
export interface Inklokke {
  id: string;
  presensie: string | Presensie;
  divisie?: (string | null) | Divisie;
  lid?: (string | null) | Lede;
  ingestuur_deur: string | User;
  tipe: 'in' | 'uit';
  scan_time: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  gps?: [number, number] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inskrywings".
 */
export interface Inskrywing {
  id: string;
  lid: string | Lede;
  kamp?: string | null;
  kamp_kursus?: string | null;
  kamp_naam?: string | null;
  kamp_begindatum?: string | null;
  kamp_einddatum?: string | null;
  kamp_ligging?: string | null;
  kurses_opsie_1?: string | null;
  skakel_vir_kurses_opsie_1?: string | null;
  kurses_opsie_2?: string | null;
  skakel_vir_kurses_opsie_2?: string | null;
  kurses_opsie_3?: string | null;
  skakel_vir_kurses_opsie_3?: string | null;
  opsies?: string | null;
  opsie_1_waglys?: string | null;
  opsie_2_waglys?: string | null;
  opsie_3_waglys?: string | null;
  products?: string | null;
  soft_shell_baadjies?: string | null;
  seejol_hemp_kort?: string | null;
  verblyfreelings?: string | null;
  vervoer_na_mosselbaai?: string | null;
  vervoer_vanaf_mosselbaai?: string | null;
  import_id?: number | null;
  import_name?: string | null;
  lid_import_ref?: string | null;
  created_on_import?: string | null;
  updated_on_import?: string | null;
  last_updated_on_import?: string | null;
  responsible_person?: number | null;
  contact_import?: number | null;
  last_timeline_activity_by?: number | null;
  stage?: string | null;
  previous_stage?: string | null;
  currency?: string | null;
  amount?: number | null;
  betaling_ontvang?: string | null;
  inskrywer_se_epos?: string | null;
  bevestigingsepos_is_gestuur?: string | null;
  kontak_tipe?: ('Volwassene' | 'Jeuglid') | null;
  addisionele_notas?: string | null;
  qr_skakel?: string | null;
  qr_prent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groepe".
 */
export interface Groepe {
  id: string;
  naam: string;
  tipe?: ('vervoer' | 'divisie' | 'divisie_subgroep' | 'tent') | null;
  subgroepe?: (string | Groepe)[] | null;
  lede?: {
    docs?: (string | Lede)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationSubscription".
 */
export interface NotificationSubscription {
  id: string;
  endpoint: string;
  expirationTime?: string | null;
  keys: {
    p256dh: string;
    auth: string;
    [k: string]: unknown;
  };
  topics?: string[] | null;
  user?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable component templates for the visual editor
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-templates".
 */
export interface PuckTemplate {
  id: string;
  /**
   * A descriptive name for this template
   */
  name: string;
  /**
   * Optional description of what this template contains
   */
  description?: string | null;
  /**
   * Category for organizing templates (e.g., "Hero", "Footer", "CTA")
   */
  category?: string | null;
  /**
   * Serialized Puck component data
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional thumbnail URL for template preview
   */
  thumbnail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country: 'ZA';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInZAREnabled?: boolean | null;
  priceInZAR?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        variantOption?: (string | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInZAREnabled?: boolean | null;
  priceInZAR?: number | null;
  relatedProducts?: (string | Product)[] | null;
  customInputs?: {
    lidnommer?: boolean | null;
    lidnommerRequired?: boolean | null;
    customPrice?: boolean | null;
    customPriceLabel?: string | null;
    customText?: boolean | null;
    customTextLabel?: string | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  categories?: (string | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        lidnommer?: string | null;
        customText?: string | null;
        customPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'ZAR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        lidnommer?: string | null;
        customText?: string | null;
        customPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'ZAR' | null;
  accessToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        lidnommer?: string | null;
        customText?: string | null;
        customPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'softycomp' | null;
  softycomp?: {
    userReference?: string | null;
    billReference?: string | null;
    shippingAddress?: {
      title?: string | null;
      firstName?: string | null;
      lastName?: string | null;
      company?: string | null;
      addressLine1?: string | null;
      addressLine2?: string | null;
      city?: string | null;
      state?: string | null;
      postalCode?: string | null;
      country?: string | null;
      phone?: string | null;
    };
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: 'ZAR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'notificationSubscription';
        value: string | NotificationSubscription;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'lede';
        value: string | Lede;
      } | null)
    | ({
        relationTo: 'inskrywings';
        value: string | Inskrywing;
      } | null)
    | ({
        relationTo: 'divisie';
        value: string | Divisie;
      } | null)
    | ({
        relationTo: 'presensie';
        value: string | Presensie;
      } | null)
    | ({
        relationTo: 'inklokke';
        value: string | Inklokke;
      } | null)
    | ({
        relationTo: 'aktiwiteit';
        value: string | Aktiwiteit;
      } | null)
    | ({
        relationTo: 'groepe';
        value: string | Groepe;
      } | null)
    | ({
        relationTo: 'puck-templates';
        value: string | PuckTemplate;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets".
 */
export interface PayloadQueryPreset {
  id: string;
  title: string;
  isShared?: boolean | null;
  access?: {
    read?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
    update?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
    delete?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
  };
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  groupBy?: string | null;
  relatedCollection: 'lede';
  /**
   * This is a temporary field used to determine if updating the preset would remove the user's access to it. When `true`, this record will be deleted after running the preset's `validate` function.
   */
  isTemp?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  puckData?: T;
  editorVersion?: T;
  pageLayout?: T;
  isHomepage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        nofollow?: T;
        excludeFromSitemap?: T;
      };
  conversionTracking?:
    | T
    | {
        isConversionPage?: T;
        conversionType?: T;
        conversionValue?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationSubscription_select".
 */
export interface NotificationSubscriptionSelect<T extends boolean = true> {
  endpoint?: T;
  expirationTime?: T;
  keys?: T;
  topics?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  tipe?: T;
  self_lid?: T;
  gekoppelde_lede?: T;
  role?: T;
  candidate_self_lid_nommer?: T;
  candidate_self_lid_dob?: T;
  candidate_self_lid_invalid_dob?: T;
  candidate_gekoppelde_lede?:
    | T
    | {
        row_id?: T;
        lid_nommer?: T;
        dob?: T;
        invalid_dob?: T;
        id?: T;
      };
  accounts?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        type?: T;
        id?: T;
      };
  sessions?:
    | T
    | {
        sessionToken?: T;
        expires?: T;
        id?: T;
      };
  verificationTokens?:
    | T
    | {
        token?: T;
        expires?: T;
        uses_remaining?: T;
        id?: T;
      };
  authenticators?:
    | T
    | {
        credentialID?: T;
        credentialPublicKey?: T;
        credentialBackedUp?: T;
        counter?: T;
        transports?: T;
        credentialDeviceType?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lede_select".
 */
export interface LedeSelect<T extends boolean = true> {
  id?: T;
  user?: T;
  divisie?: T;
  rol?: T;
  huidige_inskrywing?: T;
  naam?: T;
  van?: T;
  noemnaam?: T;
  vertoonnaam?: T;
  geboortedatum?: T;
  geslag?: T;
  skoolgraad?: T;
  posisie?: T;
  kommando?: T;
  hoeveelste_jaar_kamp_jy_op_seejol?: T;
  groepe?: T;
  lid_inligting_sigbaar_vir_groepe?: T;
  lid_eposadres?: T;
  lid_kontaknommer?: T;
  kontakpersoon_voor_kamp?: T;
  kontaknommer_voor_kamp?: T;
  eposadres_voor_kamp?: T;
  kontakpersoon_tydens_kamp?: T;
  kontaknommer_tydens_kamp?: T;
  eposadres_tydens_kamp?: T;
  ma_volle_naam?: T;
  ma_kontaknommer?: T;
  ma_eposadres?: T;
  pa_volle_naam?: T;
  pa_kontaknommer?: T;
  pa_eposadres?: T;
  voog_volle_naam?: T;
  voog_kontaknommer?: T;
  voog_eposadres?: T;
  mediese_fonds_naam?: T;
  mediese_fonds_nommer?: T;
  mediese_fonds_afhanklikheidskode?: T;
  allergiee?: T;
  mediese_kondisies?: T;
  kroniese_medikasie?: T;
  mediese_notas?: T;
  kamp?: T;
  kamp_kursus?: T;
  kamp_naam?: T;
  kamp_begindatum?: T;
  kamp_einddatum?: T;
  kamp_ligging?: T;
  kurses_opsie_1?: T;
  skakel_vir_kurses_opsie_1?: T;
  kurses_opsie_2?: T;
  skakel_vir_kurses_opsie_2?: T;
  kurses_opsie_3?: T;
  skakel_vir_kurses_opsie_3?: T;
  opsies?: T;
  opsie_1_waglys?: T;
  opsie_2_waglys?: T;
  opsie_3_waglys?: T;
  products?: T;
  soft_shell_baadjies?: T;
  seejol_hemp_kort?: T;
  verblyfreelings?: T;
  vervoer_na_mosselbaai?: T;
  vervoer_vanaf_mosselbaai?: T;
  import_id?: T;
  import_name?: T;
  lid_import_ref?: T;
  created_on_import?: T;
  updated_on_import?: T;
  last_updated_on_import?: T;
  responsible_person?: T;
  contact_import?: T;
  last_timeline_activity_by?: T;
  stage?: T;
  previous_stage?: T;
  currency?: T;
  amount?: T;
  betaling_ontvang?: T;
  inskrywer_se_epos?: T;
  bevestigingsepos_is_gestuur?: T;
  kontak_tipe?: T;
  addisionele_notas?: T;
  qr_skakel?: T;
  qr_prent?: T;
  inskrywings_geskiedenis?: T;
  syncedData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inskrywings_select".
 */
export interface InskrywingsSelect<T extends boolean = true> {
  lid?: T;
  kamp?: T;
  kamp_kursus?: T;
  kamp_naam?: T;
  kamp_begindatum?: T;
  kamp_einddatum?: T;
  kamp_ligging?: T;
  kurses_opsie_1?: T;
  skakel_vir_kurses_opsie_1?: T;
  kurses_opsie_2?: T;
  skakel_vir_kurses_opsie_2?: T;
  kurses_opsie_3?: T;
  skakel_vir_kurses_opsie_3?: T;
  opsies?: T;
  opsie_1_waglys?: T;
  opsie_2_waglys?: T;
  opsie_3_waglys?: T;
  products?: T;
  soft_shell_baadjies?: T;
  seejol_hemp_kort?: T;
  verblyfreelings?: T;
  vervoer_na_mosselbaai?: T;
  vervoer_vanaf_mosselbaai?: T;
  import_id?: T;
  import_name?: T;
  lid_import_ref?: T;
  created_on_import?: T;
  updated_on_import?: T;
  last_updated_on_import?: T;
  responsible_person?: T;
  contact_import?: T;
  last_timeline_activity_by?: T;
  stage?: T;
  previous_stage?: T;
  currency?: T;
  amount?: T;
  betaling_ontvang?: T;
  inskrywer_se_epos?: T;
  bevestigingsepos_is_gestuur?: T;
  kontak_tipe?: T;
  addisionele_notas?: T;
  qr_skakel?: T;
  qr_prent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisie_select".
 */
export interface DivisieSelect<T extends boolean = true> {
  number?: T;
  naam?: T;
  shared_contact?: T;
  lede?: T;
  aktiwiteite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presensie_select".
 */
export interface PresensieSelect<T extends boolean = true> {
  naam?: T;
  id?: T;
  presensie_tipe?: T;
  inklokke?: T;
  verwagte_lede?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inklokke_select".
 */
export interface InklokkeSelect<T extends boolean = true> {
  presensie?: T;
  divisie?: T;
  lid?: T;
  ingestuur_deur?: T;
  tipe?: T;
  scan_time?: T;
  gps?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aktiwiteit_select".
 */
export interface AktiwiteitSelect<T extends boolean = true> {
  title?: T;
  begin?: T;
  einde?: T;
  aktiwiteitType?: T;
  beskrywing?: T;
  presensie?: T;
  virAlle?: T;
  divisies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groepe_select".
 */
export interface GroepeSelect<T extends boolean = true> {
  naam?: T;
  tipe?: T;
  subgroepe?: T;
  lede?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-templates_select".
 */
export interface PuckTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  category?: T;
  content?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInZAREnabled?: T;
  priceInZAR?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInZAREnabled?: T;
  priceInZAR?: T;
  relatedProducts?: T;
  customInputs?:
    | T
    | {
        lidnommer?: T;
        lidnommerRequired?: T;
        customPrice?: T;
        customPriceLabel?: T;
        customText?: T;
        customTextLabel?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        lidnommer?: T;
        customText?: T;
        customPrice?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        lidnommer?: T;
        customText?: T;
        customPrice?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  accessToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        lidnommer?: T;
        customText?: T;
        customPrice?: T;
        id?: T;
      };
  paymentMethod?: T;
  softycomp?:
    | T
    | {
        userReference?: T;
        billReference?: T;
        shippingAddress?:
          | T
          | {
              title?: T;
              firstName?: T;
              lastName?: T;
              company?: T;
              addressLine1?: T;
              addressLine2?: T;
              city?: T;
              state?: T;
              postalCode?: T;
              country?: T;
              phone?: T;
            };
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets_select".
 */
export interface PayloadQueryPresetsSelect<T extends boolean = true> {
  title?: T;
  isShared?: T;
  access?:
    | T
    | {
        read?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        update?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        delete?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
      };
  where?: T;
  columns?: T;
  groupBy?: T;
  relatedCollection?: T;
  isTemp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google_sheets_settings".
 */
export interface GoogleSheetsSetting {
  id: string;
  /**
   * The Google Spreadsheet ID (found in the URL)
   */
  sheetId: string;
  collections: {
    slug: string;
    targets: {
      name: string;
      tabName: string;
      keyField: string;
      mapping: {
        [k: string]: string;
      };
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sas_import_settings".
 */
export interface SasImportSetting {
  id: string;
  /**
   * The full webhook URL from SAS for the REST API.
   */
  webhookUrl: string;
  kampId?: string | null;
  kampNaam?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google_sheets_settings_select".
 */
export interface GoogleSheetsSettingsSelect<T extends boolean = true> {
  sheetId?: T;
  collections?:
    | T
    | {
        slug?: T;
        targets?:
          | T
          | {
              name?: T;
              tabName?: T;
              keyField?: T;
              mapping?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sas_import_settings_select".
 */
export interface SasImportSettingsSelect<T extends boolean = true> {
  webhookUrl?: T;
  kampId?: T;
  kampNaam?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: string | Post;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}